<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.1-dev INSTALLER - Wednesday 18th of February 2015 09:17:33 AM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://localhost/hoauthmasteryii/index.php?r=site/oauth", 

		"providers" => array ( 
			// openid providers
/*
			"OpenID" => array (
				"enabled" => true
			),

			"AOL"  => array ( 
				"enabled" => true 
			),
			"Yahoo" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" )
			),
*/

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( 
					"id" => "97768727470-qnr960vg527r73gp52910igh1q03mffi.apps.googleusercontent.com", 
					"secret" => "0a30e51383ffc0f619d9054c31aae0800e06abf4" 
							)
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array (
				 		"id" => "1534503190133665", 
				 		"secret" => "c2ed70bd12e6fb1cc0fa93a389fbaa86" 

				),
//				 "scope"   => "email, user_about_me, user_birthday, user_hometown, publish_actions", // optional
				 //"scope"   => "public_profile, basic_info, user_birthday, user_religion_politics, user_relationships, user_relationship_details, user_hometown, user_location, user_likes, user_activities, user_interests, user_education_history, user_work_history, user_website, user_groups, user_events, user_photos, user_videos, user_friends, user_about_me, user_status, user_games_activity, user_tagged_places, user_actions.books, user_actions.music, user_actions.video, user_actions.news, user_actions.fitness", // optional
				"display" => "popup" // optional
			),
 
			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "oMO8chvHmskdLcIEW0X8IagZd", "secret" => "ruAxeccTi4uS5PokQWimyTnVoEhaiSNYZGlKaBH8eEuIiH3UWk" ) 
			),
			"Instagram" =>   array ( 
				"enabled"   => true,
				"keys"   => array ( "id" => "0d703d08296f4a31bc40a68a4ee60bed", "secret" => "f92c00828052406697639c7a236f1d79" )
			), 
			"Foursquare" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "SQALUPBSPPVOYTQSGTUX3J3133FY5TOQN5NLHL2IQ35BUG23", 
				"secret" => "BHGOHMS4MUYEQVWEY2MRDX0YY3L0BLBRMPXBGLD4MKOAL2XS" ) 
			),

/*

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),
			
			// windows live
			"Live" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
			"MySpace" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),
			*/
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		//"debug_file" => "/hybridauth.log"
	);
